// Express API gateway for the smart mirror camera console.
//
// Provides REST API gateway:
//   - proxies the camera supervisor (/mode, /healthz, /stream.mjpg,
//     /mirror.mjpg = live screencast of the real mirror screen) on :8001
//   - bridges MQTT: publish test messages (/api/mqtt/publish) and stream all
//     smartmirror/# traffic to the browser over SSE (/api/mqtt/stream)
//   - AI module builder (Claude Agent SDK)
// The UI is served separately by mirrorControl on :8090.

const path = require("path");
const fs = require("fs");
const express = require("express");
const { createProxyMiddleware } = require("http-proxy-middleware");
const mqtt = require("mqtt");

// Load server/.env into process.env (dependency-free). systemd's EnvironmentFile
// only works if the unit was (re)generated by setup.sh; deploy.sh restarts the
// service without rewriting the unit, so we also load it here. Tolerates a
// leading `export` and surrounding quotes; never overrides an already-set var.
(function loadEnv() {
  try {
    for (const raw of fs.readFileSync(path.join(__dirname, ".env"), "utf8").split("\n")) {
      const line = raw.trim();
      if (!line || line.startsWith("#")) continue;
      const m = line.match(/^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
      if (!m) continue;
      const v = m[2].replace(/^(['"])([\s\S]*)\1$/, "$2");
      if (process.env[m[1]] === undefined) process.env[m[1]] = v;
    }
  } catch {
    /* no .env — fine */
  }
})();

const { mountModuleAI } = require("./module-ai");

const PORT = parseInt(process.env.PORT || "8000", 10);
const HOST = process.env.HOST || "0.0.0.0";
const BACKEND = process.env.BACKEND || "http://127.0.0.1:8001";
const MQTT_URL = process.env.MQTT_URL || "mqtt://127.0.0.1:1883";

const app = express();

// --- MQTT bridge ---------------------------------------------------------
const mqttClient = mqtt.connect(MQTT_URL, { reconnectPeriod: 2000 });
let mqttConnected = false;
const sseClients = new Set();

mqttClient.on("connect", () => {
  mqttConnected = true;
  console.log(`mqtt connected: ${MQTT_URL}`);
  mqttClient.subscribe("smartmirror/#");
});
mqttClient.on("reconnect", () => console.log("mqtt reconnecting…"));
mqttClient.on("close", () => {
  mqttConnected = false;
});
mqttClient.on("error", (e) => console.error("mqtt error:", e.message));

// Fan out every smartmirror/# message to connected SSE clients (live monitor).
mqttClient.on("message", (topic, payload) => {
  const line = `data: ${JSON.stringify({
    ts: Date.now(),
    topic,
    payload: payload.toString(),
  })}\n\n`;
  for (const res of sseClients) res.write(line);
});

// --- supervisor proxy ----------------------------------------------------
// Mounted at root with a pathFilter so the full path is preserved and the
// MJPEG stream is piped untouched. Must come before express.json() so the
// proxied POST /mode body streams through intact.
app.use(
  createProxyMiddleware({
    target: BACKEND,
    changeOrigin: true,
    ws: false,
    pathFilter: (p) =>
      p === "/mode" ||
      p === "/healthz" ||
      p === "/resolution" ||
      p.startsWith("/stream.mjpg") ||
      // live screencast of the real mirror screen (see backend/mirror_capture.py)
      p.startsWith("/mirror.mjpg") ||
      p.startsWith("/mirror.jpg") ||
      p === "/capture" ||
      p === "/encode" ||
      p.startsWith("/dataset") ||
      p.startsWith("/photo") ||
      p.startsWith("/profiles") ||
      p === "/radar" ||
      p === "/modules" ||
      p.startsWith("/layout") ||
      (p.startsWith("/store") && !p.startsWith("/store-assets")),
  })
);

app.use(express.json());

// --- MQTT API ------------------------------------------------------------
app.get("/api/mqtt/status", (_req, res) => {
  res.json({ connected: mqttConnected, url: MQTT_URL });
});

app.post("/api/mqtt/publish", (req, res) => {
  const { topic, payload } = req.body || {};
  if (!topic) return res.status(400).json({ error: "topic required" });
  const msg =
    typeof payload === "string" ? payload : JSON.stringify(payload ?? "");
  mqttClient.publish(topic, msg, { qos: 1 }, (err) => {
    if (err) return res.status(500).json({ error: err.message });
    res.json({ ok: true, topic, payload: msg });
  });
});

app.get("/api/mqtt/subscribe", (req, res) => {
  const { topic, count = "1", timeout = "5000" } = req.query;
  if (!topic) return res.status(400).json({ error: "topic required" });

  const maxCount = parseInt(count, 10);
  const maxTimeout = parseInt(timeout, 10);
  const messages = [];
  let timer;
  let finished = false;

  const handler = (t, payload) => {
    if (finished) return;
    if (t === topic || (topic.endsWith("/#") && t.startsWith(topic.slice(0, -2)))) {
      messages.push({ topic: t, payload: payload.toString() });
      if (messages.length >= maxCount) {
        finish();
      }
    }
  };

  const finish = () => {
    if (finished) return;
    finished = true;
    clearTimeout(timer);
    mqttClient.off("message", handler);
    res.json({ messages });
  };

  mqttClient.on("message", handler);
  timer = setTimeout(finish, maxTimeout);

  req.on("close", finish);
});

// --- AI module builder (chat with Claude to scaffold new modules) --------
mountModuleAI(app, express);

// Server-Sent Events: live feed of all smartmirror/# traffic.
app.get("/api/mqtt/stream", (req, res) => {
  res.set({
    "Content-Type": "text/event-stream",
    "Cache-Control": "no-cache",
    Connection: "keep-alive",
  });
  if (res.flushHeaders) res.flushHeaders();
  res.write(
    `data: ${JSON.stringify({ ts: Date.now(), system: "connected" })}\n\n`
  );
  sseClients.add(res);
  req.on("close", () => sseClients.delete(res));
});

// --- store assets (store/modules/ in repo root) --------------------------
const REPO_ROOT = path.join(__dirname, "..", "..");
app.use("/store-assets", express.static(path.join(REPO_ROOT, "store", "modules")));

// --- health check / API status -------------------------------------------
app.get("/", (_req, res) => {
  res.json({
    service: "mirror-console-web",
    description: "REST API gateway for smart mirror (UI on :8090)",
    endpoints: {
      supervisor: `${BACKEND} (proxied: /mode, /healthz, /stream.mjpg, /capture, /dataset, /profiles, /radar, /layout, /store, /modules)`,
      mqtt: "/api/mqtt/* (status, publish, subscribe, stream)",
      ai: "/api/modules/* (AI module builder)",
      storeAssets: "/store-assets/* (module screenshots)"
    },
    mqtt: {
      connected: mqttConnected,
      url: MQTT_URL
    }
  });
});

app.listen(PORT, HOST, () => {
  console.log(`mirror-console API gateway on http://${HOST}:${PORT} -> ${BACKEND}`);
  console.log(`UI served on http://${HOST}:8090 (mirrorControl)`);
});
