import type { Lang } from "@/types";

// Flat bilingual dictionary, ported 1:1 from the prototype LABELS. Numbers,
// labels and statuses render in Space Mono; sentences in Space Grotesk.
export interface LabelDict {
  [key: string]: string | string[];
}

export const LABELS: Record<Lang, LabelDict> = {
  cs: {
    navMirror: "Zrcadlo", navLayouts: "Scény", navModules: "Widgety", navProfiles: "Profily", navRadar: "Radar", navCamera: "Kamera", navComms: "Komunikace", online: "online",
    editLayout: "Upravit scénu", wake: "Probudit", currentInfo: "Aktuální informace", activeScene: "Aktivní scéna", profile: "Profil", connection: "Připojení", modsRunning: "Widgety v provozu",
    changesA: "nepublikovaných změn.", changesB: "Náhled výše je živý stav zrcadla.", apply: "Aplikovat",
    winTitle: "Časová okna", winEyebrow: "default · kdy se co zobrazí", addWindow: "Přidat časové okno",
    winHint: "Okno určuje časový úsek dne. Po vytvoření okna rovnou upravíš jeho rozložení widgetů.", applyToMirror: "Aplikovat na zrcadlo",
    layoutsTitle: "Scény", sceneBtn: "Scéna", layoutsHint: "Vytvořte nebo upravte scénu, kterou uvidí všichni uživatelé.", nsTitle: "Nová scéna", nsNameLabel: "Název scény", nsNamePh: "např. Ranní", nsTimeLabel: "Čas zobrazení", nsFrom: "Od", nsTo: "Do", nsCreate: "Vytvořit", teTitle: "Upravit čas zobrazení", teSave: "Uložit", teInvalidMsg: "Konec musí být po začátku.", nsOverlap: "Scény se nemůžou překrývat.", nsOverlapA: "Čas se překrývá se scénou", nsOverlapB: ". Scény se nesmí překrývat.",
    onMirror: "na zrcadle", allDay: "Celý den", loadingMirror: "Synchronizuji zrcadlo", modulesWord: "widgetů", moreWidgets: "Další widgety", usedBadge: "Použito", removeBadge: "Odebrat", markedBadge: "Označeno", zoneAllUsedMsg: "Všechny nainstalované widgety už v této scéně používáš.", paletteHint: "Paleta — klepni widget, pak + v cílové pozici", del: "Smazat", saveScene: "Uložit scénu", heldPickA: "Držíš", heldMoveA: "Přesouváš", heldHint: "Klepni na + v cílové pozici", heldDelete: "Vymazat", cancel: "Zrušit", delConfirmTitle: "Opravdu smazat scénu?", delConfirmA: "Scéna", delConfirmB: "bude trvale odstraněna. Tuto akci nelze vrátit zpět.", ebTitle: "Neuložené změny", ebMsg: "V této scéně máš neuložené změny. Chceš je uložit, nebo zahodit?", ebSave: "Uložit změny", ebDiscard: "Zahodit změny", libraryTitle: "Knihovna widgetů", canvasLabel: "Rozložení na zrcadle", zoneEyebrow: "Pole na zrcadle", zoneAddTitle: "Přidat widget do pole", zoneEmptyMsg: "Zatím tu nejsou žádné widgety. Přidej je níže.", zoneOrder: "Pořadí · klepni šipky", added: "přidáno", done: "Hotovo", cfgTitle: "Nastavení widgetu", cfgHint: "Tento widget vyžaduje nastavení. Vyplň pole níže, ať ho můžeme přidat.", cfgAdd: "Přidat widget", cfgReq: "povinné", cfgMissing: "Vyplň prosím všechna povinná pole.",
    modulesTitle: "Widgety", createAI: "Vytvořit widget (AI)", pillMine: "Moje", pillInstalled: "Instalované", pillSearch: "Prohledat", communityBy: "vytvořeno komunitou",
    searchPh: "Hledat v 1412 widgetech…", searchCancel: "Zrušit", kbSpace: "mezera", kbSearch: "Hledat", noResults: "Nic nenalezeno. Zkus jiný výraz nebo vytvoř widget přes AI.",
    installed: "Instalováno", install: "Nainstalovat", edit: "Upravit", uninstall: "Odinstalovat", remove: "Odstranit", preview: "Náhled", live: "živě", category: "Kategorie",
    unConfirmTitle: "Odinstalovat widget?", unConfirmA: "Widget", unConfirmB: "bude odebrán ze zrcadla. Můžeš ho kdykoli znovu nainstalovat.",
    delModBtn: "Smazat", delModHint: "Tento widget jsi vytvořil ty. Smazání je nevratné.", removeHint: "Odstraněním se widget odebere ze zrcadla. Můžeš ho kdykoli znovu nainstalovat.", delModTitle: "Smazat widget?", delModA: "Widget", delModB: "bude trvale smazán a odebrán ze všech scén.", delModWarn: "Jde o tvůj vlastní widget — po smazání ho nelze obnovit.",
    newModule: "Nový widget (AI)", newModuleHint: "Chybí vám widget? Jednoduše si ho vytvořte pomocí AI asistenta.", createSecNew: "Nový widget", createSecDrafts: "Rozpracované widgety", draftBadge: "Rozpracováno", draftsEmpty: "Zatím nemáš žádné rozpracované widgety.", modName: "Jméno widgetu", modNamePh: "např. Připomínky", modDo: "Co má widget dělat / zobrazovat", modDoPh: "např. Chci, aby se mi na zrcadle zobrazovaly mé připomínky, které mám označené jako důležité.", createContinue: "Vytvořit a pokračovat →",
    wsReadyA: "Widget", wsReadyB: "připraven. Popiš, co má zobrazovat a jak má vypadat.", ctrlTitle: "Ovladač", ctrlHint: "Ovladač widgetu — slouží pouze k ovládání v tomto náhledu při vytváření. Na zrcadle zobrazen nebude.", ctrlImportant: "Jen důležité připomínky", ctrlMax: "Max. počet položek", addCtrl: "Přidat ovladač", ctrlMsg: "Přidej ovládací prvek", ctrlIntro: "Jasně! Odpověz prosím na pár otázek, ať ovladač přesně sedne.", ctrlFormTitle: "Pár otázek k ovladači", aiAgent: "AI agent", agentStep1: "Analyzuji tvůj požadavek…", agentStep2: "Navrhuji strukturu widgetu…", agentStep3: "Generuji kód a styly…", agentStep4: "Sestavuji živý náhled…", agentWorking: "AI agent pracuje…", agentReadyBar: "Widget je připraven · otevřít", cfQ1: "Co se má ovládat?", cfQ1Ph: "např. zobrazení důležitých připomínek", cfQ2: "Typ ovladače", cfTypeToggle: "Přepínač", cfTypeSelect: "Výběr", cfTypeSlider: "Posuvník", cfQ3: "Výchozí hodnota", cfQ3Ph: "např. Zapnuto", cfSubmit: "Odeslat", ctrlAck: "Díky! Ovladač podle zadání připravím.", wsBackTitle: "Uložit widget?", wsBackMsg: "Chceš tento widget uložit do konceptů, nebo ho rovnou nainstalovat na zrcadlo?", wsSaveDraft: "Uložit do konceptů", wsInstallNew: "Instalovat widget", wsComposer: "Napiš, co změnit…", toMirror: "Instalovat", tabChat: "Chat", tabPreview: "Náhled", wsBot: "Hotovo — widget jsem upravil. Můžeš ho přidat do scény.", wsSuggest: ["Větší číslo", "Přidej popisek", "Tmavší pozadí"],
    profilesTitle: "Profily", profileBtn: "Profil", npStep: "Krok", npTitle: "Nový profil", npNameTitle: "Pojmenuj profil", npNameHint: "Jméno člověka, kterého má zrcadlo po rozpoznání obličeje poznat.", npNamePh: "např. Tomáš", npPhotosTitle: "Fotky pro rozpoznání", npPhotosHint: "Pořiď několik fotek obličeje, podle kterých tě zrcadlo rozpozná. Čím víc úhlů, tím lépe.", npScenesTitle: "Přidej scény", npScenesHint: "Vyber scény, které se na tomto profilu mají zobrazovat. Scény je možné kdykoliv přidat nebo upravit v detailu profilu.", npNext: "Pokračovat", npSkip: "Přeskočit", npCreate: "Vytvořit profil", npTakePhoto: "Pořídit fotku", npSheetDone: "Hotovo", npNoScenes: "Žádné dostupné scény.", photosWord: "fotek", scenesWord: "scén", profilesHint: "Přidejte nebo upravte profil a přizpůsobte si, co se uživateli po rozpoznání obličeje na zrcadle zobrazí.",
    defaultTag: "výchozí", defaultRuns: "Běží, když zrcadlo nikoho nerozpozná · 1 okno", elProfile: "3 okna · ráno / večer / víkend", elPhotos: "12 fotek",
    profScenes: "Scény", profScenesHint: "Rozvrhněte si, co se na profilu kdy zobrazí.", profFaceHint: "Obličeje, podle kterých zrcadlo profil rozpozná.", faceRecog: "Rozpoznání obličeje", profSettingsTab: "Nastavení", tempActivateTitle: "Dočasně aktivovat", tempActivateDesc: "Dočasně zobrazí tento profil na zrcadle a ignoruje reálná data z radaru a kamery. Vhodné pro vyzkoušení profilu.", tempActivate: "Dočasně aktivovat", tempActiveOn: "Dočasně aktivní · ukončit", deleteProfileTitle: "Odstranit profil", deleteProfileDesc: "Trvale odstraní tento profil včetně jeho rozpoznávacích fotek. Tuto akci nelze vrátit zpět.", deleteProfileBtn: "Odstranit", delProfA: "Profil", delProfB: "bude trvale odstraněn i s jeho fotkami.", faceDesc: "Výchozí profil se zobrazí, když není rozpoznán žádný obličej. Nelze ho odebrat.", addPhotos: "Přidat fotky", retrain: "Přetrénovat", photosTitle: "Fotky", faceHint: "Přidáním dalších fotek zlepšíte rozpoznávací funkce.", photoWord: "Foto", photoTaken: "Pořízeno", addPhotosTitle: "Přidat fotky", addPhotosHint: "Vyberte zdroj, odkud chcete přidat fotky pro rozpoznání obličeje.", srcMirrorTitle: "Kamera na zrcadle", srcMirrorSub: "Pořiďte fotku přímo zrcadlem", srcPhoneTitle: "Fotky z mobilu", srcPhoneSub: "Nahrajte fotky z galerie telefonu", takePhoto: "Pořídit fotku", choosePhotos: "Vybrat fotky", shootPhoto: "Vyfotit", sessionTitle: "Právě pořízené", usePhotos: "Použít fotky", taskRetrain: "Aplikuji novou sadu fotek pro rozpoznání obličeje…", taskNewProfile: "Vytvářím profil {name} a trénuji rozpoznávání obličeje…", taskInstall: "Instaluji widget", installing: "Instaluji…", camPreviewHint: "Náhled kamery zrcadla", removePhoto: "Odstranit", photoDelTitle: "Odstranit fotku?", photoDelMsg: "bude trvale odstraněna z tohoto profilu. Tuto akci nelze vrátit zpět.", plan: "Plán — kdy a co", addWin2: "+ Přidat okno",
    settings: "Nastavení", back: "Zpět", setMirror: "Zrcadlo", setLangHead: "Jazyk", setLang: "Jazyk aplikace", setLangSub: "čeština / angličtina", setConn: "Připojení", setConnSub: "192.168.1.42 · online", setRadar: "Radar", setRadarSub: "detekce přítomnosti", setFace: "Rozpoznávání obličeje", setFaceSub: "on-device model", setNight: "Noční ztlumení", setNightSub: "22:00–06:00", connSearch: "Vyhledat zrcadlo", connScanning: "Prohledávám síť…", connRescan: "Hledat znovu", connIdleSub: "Zrcadlo zatím nepřipojeno", connScanSub: "kontroluji zařízení v síti", tMirrorFound: "Zrcadlo nalezeno",
    tApplied: "Aplikováno na zrcadlo", tProfileAdded: "Profil vytvořen", tProfileTrained: "Profil je připraven", tTempOn: "Profil dočasně aktivován", tTempOff: "Dočasná aktivace ukončena", tProfileDeleted: "Profil odstraněn", tWake: "Zrcadlo probuzeno", tSceneDel: "Scéna smazána", tSceneSaved: "Scéna uložena", tMoved: "Přesunuto", tAdded: "Přidáno", tSelect: "Vyber widget z palety", tNewScene: "Nová scéna", tUninstall: "Odinstalováno", tModDeleted: "Widget smazán", tRemovedScene: "Odebráno ze scény", tPhotoDel: "Fotka odstraněna", tPhotoTaken: "Fotka pořízena", tPhotoAdded: "Fotka přidána", tRetrain: "Přetrénování spuštěno", tTaskDone: "Přetrénování dokončeno", tInstalled: "Widget nainstalován", tDraftSaved: "Uloženo do konceptů", tAddCtrl: "Přidej požadavek na ovladač do chatu", tInstall: "Nainstalováno", tInstallMirror: "Nainstalováno na zrcadlo", tAddProfile: "Přidat profil", tChooseScene: "Vyber scénu", devEyebrow: "Vývojář", devTitle: "Zadej heslo", devWrong: "Nesprávné heslo. Zkus to znovu.", devUnlock: "Odemknout", tDevOn: "Dev mód zapnut",
  },
  en: {
    navMirror: "Mirror", navLayouts: "Scenes", navModules: "Widgets", navProfiles: "Profiles", navRadar: "Radar", navCamera: "Camera", navComms: "Comms", online: "online",
    editLayout: "Edit scene", wake: "Wake up", currentInfo: "Current information", activeScene: "Active scene", profile: "Profile", connection: "Connection", modsRunning: "Widgets running",
    changesA: "unpublished changes.", changesB: "Preview above is the live mirror state.", apply: "Apply",
    winTitle: "Time windows", winEyebrow: "default · when things show", addWindow: "Add time window",
    winHint: "A window defines a time range of the day. After creating one you edit its widget layout right away.", applyToMirror: "Apply to mirror",
    layoutsTitle: "Scenes", sceneBtn: "Scene", layoutsHint: "A scene is a reusable widget arrangement. Profiles and schedules only reference it.", nsTitle: "New scene", nsNameLabel: "Scene name", nsNamePh: "e.g. Morning", nsTimeLabel: "Display time", nsFrom: "From", nsTo: "To", nsCreate: "Create", teTitle: "Edit display time", teSave: "Save", teInvalidMsg: "End must be after start.", nsOverlap: "Scenes cannot overlap.", nsOverlapA: "Time overlaps scene", nsOverlapB: ". Scenes cannot overlap.",
    onMirror: "on mirror", allDay: "All day", loadingMirror: "Syncing mirror", modulesWord: "widgets", moreWidgets: "More widgets", usedBadge: "In use", removeBadge: "Remove", markedBadge: "Selected", zoneAllUsedMsg: "All installed widgets are already used in this scene.", paletteHint: "Palette — tap a widget, then + in the target region", del: "Delete", saveScene: "Save scene", heldPickA: "Holding", heldMoveA: "Moving", heldHint: "Tap + in the target region", heldDelete: "Delete", cancel: "Cancel", delConfirmTitle: "Delete this scene?", delConfirmA: "Scene", delConfirmB: "will be permanently removed. This action cannot be undone.", ebTitle: "Unsaved changes", ebMsg: "You have unsaved changes in this scene. Save them or discard?", ebSave: "Save changes", ebDiscard: "Discard changes", libraryTitle: "Widget library", canvasLabel: "Layout on the mirror", zoneEyebrow: "Mirror zone", zoneAddTitle: "Add a widget to the zone", zoneEmptyMsg: "No widgets here yet. Add some below.", zoneOrder: "Order · tap the arrows", added: "added", done: "Done", cfgTitle: "Widget settings", cfgHint: "This widget needs configuration. Fill the fields below so we can add it.", cfgAdd: "Add widget", cfgReq: "required", cfgMissing: "Please fill all required fields.",
    modulesTitle: "Widgets", createAI: "Create widget (AI)", pillMine: "Mine", pillInstalled: "Installed", pillSearch: "Browse", communityBy: "by the community",
    searchPh: "Search 1412 widgets…", searchCancel: "Cancel", kbSpace: "space", kbSearch: "Search", noResults: "Nothing found. Try another term or create a widget with AI.",
    installed: "Installed", install: "Install", edit: "Edit", uninstall: "Uninstall", remove: "Remove", preview: "Preview", live: "live", category: "Category",
    unConfirmTitle: "Uninstall widget?", unConfirmA: "Widget", unConfirmB: "will be removed from the mirror. You can reinstall it anytime.",
    delModBtn: "Delete", delModHint: "You created this widget. Deleting it is permanent.", removeHint: "Removing takes the widget off the mirror. You can reinstall it anytime.", delModTitle: "Delete widget?", delModA: "Widget", delModB: "will be permanently deleted and removed from all scenes.", delModWarn: "This is your own widget — it cannot be recovered once deleted.",
    newModule: "New widget (AI)", newModuleHint: "Missing a widget? Simply create one with the AI assistant.", createSecNew: "New widget", createSecDrafts: "Work-in-progress widgets", draftBadge: "Draft", draftsEmpty: "You have no work-in-progress widgets yet.", modName: "Widget name", modNamePh: "e.g. Reminders", modDo: "What should the widget do / show", modDoPh: "e.g. I want my reminders marked as important to show on the mirror.", createContinue: "Create and continue →",
    wsReadyA: "Widget", wsReadyB: "is ready. Describe what it should show and how it should look.", ctrlTitle: "Controller", ctrlHint: "Widget controller — only controls this preview while building. It won't appear on the mirror.", ctrlImportant: "Only important reminders", ctrlMax: "Max items", addCtrl: "Add control", ctrlMsg: "Add a control element", ctrlIntro: "Sure! Answer a few questions so the control fits exactly.", ctrlFormTitle: "A few questions about the control", aiAgent: "AI agent", agentStep1: "Analyzuji tvůj požadavek…", agentStep2: "Navrhuji strukturu widgetu…", agentStep3: "Generuji kód a styly…", agentStep4: "Sestavuji živý náhled…", agentWorking: "AI agent pracuje…", agentReadyBar: "Widget je připraven · otevřít", cfQ1: "What should it control?", cfQ1Ph: "e.g. showing important reminders", cfQ2: "Control type", cfTypeToggle: "Toggle", cfTypeSelect: "Select", cfTypeSlider: "Slider", cfQ3: "Default value", cfQ3Ph: "e.g. On", cfSubmit: "Send", ctrlAck: "Thanks! I'll build the control as described.", wsBackTitle: "Save widget?", wsBackMsg: "Do you want to save this widget to drafts, or install it on the mirror right away?", wsSaveDraft: "Save to drafts", wsInstallNew: "Install widget", wsComposer: "Type what to change…", toMirror: "Install", tabChat: "Chat", tabPreview: "Preview", wsBot: "Done — I updated the widget. You can add it to a scene.", wsSuggest: ["Bigger number", "Add a label", "Darker background"],
    profilesTitle: "Profiles", profileBtn: "Profile", npStep: "Step", npTitle: "New profile", npNameTitle: "Name the profile", npNameHint: "The name of the person the mirror should recognise by their face.", npNamePh: "e.g. Tom", npPhotosTitle: "Recognition photos", npPhotosHint: "Capture a few face photos the mirror will use to recognise you. More angles, better results.", npScenesTitle: "Add scenes", npScenesHint: "Pick the scenes to show on this profile. You can skip this step.", npNext: "Continue", npSkip: "Skip", npCreate: "Create profile", npTakePhoto: "Take photo", npSheetDone: "Done", npNoScenes: "No scenes available.", photosWord: "photos", scenesWord: "scenes", profilesHint: "Add or edit a profile to customise what each person sees on the mirror once their face is recognised.",
    defaultTag: "default", defaultRuns: "Runs when the mirror recognises no one · 1 window", elProfile: "3 windows · morning / evening / weekend", elPhotos: "12 photos",
    profScenes: "Scenes", profScenesHint: "Schedule what shows on this profile and when.", profFaceHint: "Faces the mirror uses to recognise this profile.", faceRecog: "Face recognition", profSettingsTab: "Settings", tempActivateTitle: "Temporarily activate", tempActivateDesc: "Temporarily shows this profile on the mirror and ignores real radar and camera data. Handy for testing a profile.", tempActivate: "Temporarily activate", tempActiveOn: "Temporarily active · stop", deleteProfileTitle: "Delete profile", deleteProfileDesc: "Permanently deletes this profile including its recognition photos. This cannot be undone.", deleteProfileBtn: "Delete", delProfA: "Profile", delProfB: "will be permanently deleted along with its photos.", faceDesc: "The default profile shows when no face is recognised. It cannot be removed.", addPhotos: "Add photos", retrain: "Retrain", photosTitle: "Photos", faceHint: "Adding more photos improves recognition accuracy.", photoWord: "Photo", photoTaken: "Captured", addPhotosTitle: "Add photos", addPhotosHint: "Choose where to add face-recognition photos from.", srcMirrorTitle: "Mirror camera", srcMirrorSub: "Capture a photo with the mirror", srcPhoneTitle: "Photos from phone", srcPhoneSub: "Upload photos from your phone gallery", takePhoto: "Take photo", choosePhotos: "Choose photos", shootPhoto: "Take photo", sessionTitle: "Just captured", usePhotos: "Use photos", taskRetrain: "Applying new photo set for face recognition…", taskNewProfile: "Creating profile {name} and training face recognition…", taskInstall: "Installing widget", installing: "Installing…", camPreviewHint: "Mirror camera preview", removePhoto: "Remove", photoDelTitle: "Remove photo?", photoDelMsg: "will be permanently removed from this profile. This action cannot be undone.", plan: "Schedule — when and what", addWin2: "+ Add window",
    settings: "Settings", back: "Back", setMirror: "Mirror", setLangHead: "Language", setLang: "App language", setLangSub: "Czech / English", setConn: "Connection", setConnSub: "192.168.1.42 · online", setRadar: "Radar", setRadarSub: "presence detection", setFace: "Face recognition", setFaceSub: "on-device model", setNight: "Night dimming", setNightSub: "22:00–06:00", connSearch: "Find mirror", connScanning: "Scanning network…", connRescan: "Scan again", connIdleSub: "Mirror not connected yet", connScanSub: "checking devices on the network", tMirrorFound: "Mirror found",
    tApplied: "Applied to mirror", tProfileAdded: "Profile created", tProfileTrained: "Profile is ready", tTempOn: "Profile temporarily active", tTempOff: "Temporary activation ended", tProfileDeleted: "Profile deleted", tWake: "Mirror woken up", tSceneDel: "Scene deleted", tSceneSaved: "Scene saved", tMoved: "Moved", tAdded: "Added", tSelect: "Pick a widget from the palette", tNewScene: "New scene", tUninstall: "Uninstalled", tModDeleted: "Widget deleted", tRemovedScene: "Removed from scene", tPhotoDel: "Photo removed", tPhotoTaken: "Photo captured", tPhotoAdded: "Photo added", tRetrain: "Retraining started", tTaskDone: "Retraining complete", tInstalled: "Widget installed", tDraftSaved: "Saved to drafts", tAddCtrl: "Describe the control you need in chat", tInstall: "Installed", tInstallMirror: "Installed on mirror", tAddProfile: "Add profile", tChooseScene: "Pick a scene", devEyebrow: "Developer", devTitle: "Enter password", devWrong: "Wrong password. Try again.", devUnlock: "Unlock", tDevOn: "Dev mode on",
  },
};
